name: CapitalismCraft
version: 1.0
author: cocoraid
main: fr.cocoraid.capitalismcraft.CapitalismCraft
api-version: 1.13
depend: [Multiverse-Core]
softdepend: [Vault,EssentialsX, WorldGuard, WorldEdit]
commands:
  cc:
